input: ../data/encyclopedia.json
template: templates/encyclopedia.html.j2
output: ../docs/encyclopedia.html

template_dirs:
  - templates

context:
  title: "Enciclopédia Bororo"
  page: "encyclopedia"
